### ISSUE TITLE
how to display the rresults?

### ISSUE THREAD

**Issue by isalirezag** [vsakkas/selective-search#1]
Hey,
how can I display the input image like what you showed here with the selected regions on it?

**Comment by vsakkas** [comment]
Hi,
In order to display the generated rectangles you can use `matplotlib` as it can been seen in [example.py](https://github.com/vsakkas/selective-search/blob/master/example/example.py).

**Comment by isalirezag** [comment]
can you please tell me img_lbl shows?
and also what is size ?

when you display the regions[:5], one of the output is called size, can you tell me what is size? 
at first, i thought it is the size of the area of the box, but then i realized it cannot be that because for example: for the 'rect': (0, 0, 15, 26),   the area is  15x26 which is different from the size (313)...
Thanks

**Comment by vsakkas** [comment]
Hi again and sorry for the late reply. Here's a short explanation based on the paper that this implementation is based on:

Selective search uses the color and texture of an image to extract certain regions and then merges them into the boxes that you see. As the paper states: "The size of a component after a merge is simply the sum of the sizes of the two components being merged", so if you need the actual number of pixels in the image you will have to manually calculate it using the values that the `selective_search` function returns. I know this is a little confusing, but since the implementation that this repo is based on returns this parameter I decided to keep it this way.

As for the `img_lbl`, this is generated by the algorithm of Felzenswalb and Huttenlocher which is used in the `_generate_segments`. Those labels are used inside the selective_search function in order to generate the boxes that you in the end result. Again, I am not sure as to why would someone need to use these values outside the selective_search function, but I also didn't want to remove any functionality that may be of some usage to someone else.

To keep it short, if all you need to do is to segment an image into regions, then the `min_x`, `mix_y`, `max_x`, `max_y` (the first four values of `regions`) values are probably all you need.

Hope that helped clear up some things.
